name: Build ESP32-S3 DSP
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/actions/setup-arduino-cli@v1
      - name: Install core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
      - name: Compile
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32s3:FlashSize=16M,PartitionScheme=default_16MB,PSRAM=enabled -e.
